name: Deploy Frontend
on:
  push:
    branches:
      - master # Note: You might need to change this to 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # This is the corrected login step
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Docker image
        run: docker build -t azsure/react-test -f Dockerfile.dev .
      
      - name: Run tests inside container
        run: docker run -e CI=true azsure/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einars/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-us-east-2-271692926412
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
