name: Deploy Frontend
on:
  push:
    branches:
      - master # Note: You might need to change this to 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # This is the corrected login step
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Docker image
        run: docker build -t azsure/react-test -f Dockerfile.dev .
      
      - name: Run tests inside container
        run: docker run -e CI=true azsure/react-test npm test